### PR TITLE
fix: enforce file extensions in imports

### PR DESCRIPTION
**Pull request by limonte**
The current dist files don't have extensions in them, e.g. here: https://cdn.jsdelivr.net/npm/email-misspelled@4.2.0/dist/esm/index.js

```js
import { emailMisspelled } from "./email-misspelled";
export * from "./domains";
export * from "./typings";
```

Many projects will be unable to build that because of missing extensions, for example my project with Webpack 5 is expecting this:

```js
import { emailMisspelled } from "./email-misspelled.js";
export * from "./domains/index.js";
export * from "./typings/index.js";
```

Without extensions it failing with this messages:

```
ERROR in ./node_modules/email-misspelled/dist/esm/index.js 1:0-53
Module not found: Error: Can't resolve './email-misspelled' in '/private/var/www/english-online/node_modules/email-misspelled/dist/esm'
Did you mean 'email-misspelled.js'?
BREAKING CHANGE: The request './email-misspelled' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

This PR will fix that.

### CODE REVIEW

**Comment by limonte** [comment]
Oh, I'm also using https://www.npmjs.com/package/eslint-plugin-require-extensions to make sure eslint automatically fixing imports and preventing invalid one from being added in the future.

**Comment by limonte** [comment]
here's how files in the `dist` folder will look like after this change:

```diff
/* eslint import/no-default-export: 0 */
- import { emailMisspelled } from "./email-misspelled"
+ import { emailMisspelled } from "./email-misspelled.js"

- export * from "./domains"
- export * from "./typings"
+ export * from "./domains/index.js"
+ export * from "./typings/index.js"
export default emailMisspelled
```

**Comment by limonte** [comment]
ping @julien-amblard 🙌

**Comment by julien-amblard** [comment]
Hello, 
Sorry I've very busy this week.   
I'll merge this for now but I would rather find a way to add extensions in build time instead of source file. I'm really not a fan of having `.js` extension while it's `.ts` file. It's confusing

**Review by julien-amblard — APPROVED** [review]

**Comment by limonte** [comment]
I totally agree with you, I checked `tsc` for the option to add extensions when building, but wasn't able to find one.

**Pull request merged**
